import { Link } from "wouter";
import { LockKeyhole, ArrowLeft, RefreshCw } from "lucide-react";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";

const statusLabel: Record<string, string> = { pending: "Pendente", in_process: "Em análise", approved: "Aprovado", rejected: "Recusado", cancelled: "Cancelado", refunded: "Estornado", unknown: "Desconhecido" };

export default function AdminOrders() {
  const { user, loading } = useAuth();
  const orders = trpc.orders.adminList.useQuery(undefined, { enabled: Boolean(user?.role === "admin") });
  if (loading) return <div className="min-h-screen bg-[#08090d] p-10 text-white/50">Carregando acesso...</div>;
  if (!user || user.role !== "admin") return <div className="flex min-h-screen items-center justify-center bg-[#08090d] px-5 text-center text-white"><div><LockKeyhole className="mx-auto h-10 w-10 text-[#6df4ff]" /><h1 className="mt-5 text-3xl font-black">Área restrita</h1><p className="mt-3 text-white/50">Entre com a conta administradora da loja para acessar os pedidos.</p><Link href="/" className="mt-6 inline-flex rounded-xl bg-[#6df4ff] px-5 py-3 text-xs font-black uppercase tracking-widest text-[#071017]">Voltar para a loja</Link></div></div>;
  return <div className="min-h-screen bg-[#08090d] text-white"><header className="border-b border-white/10"><div className="container flex h-20 items-center justify-between"><div><div className="text-[10px] font-black uppercase tracking-[0.18em] text-[#6df4ff]">Gamers RTF</div><h1 className="mt-1 text-xl font-black">Pedidos</h1></div><div className="flex items-center gap-3"><button onClick={() => orders.refetch()} className="icon-button" aria-label="Atualizar pedidos"><RefreshCw className="h-4 w-4" /></button><Link href="/" className="flex items-center gap-2 text-xs font-black uppercase tracking-widest text-white/55 hover:text-white"><ArrowLeft className="h-4 w-4" /> Loja</Link></div></div></header><main className="container py-10">{orders.isLoading ? <p className="text-white/50">Carregando pedidos...</p> : orders.isError ? <p className="text-[#ff9ba8]">Não foi possível carregar os pedidos.</p> : orders.data?.length === 0 ? <div className="rounded-3xl border border-white/10 bg-white/[0.03] p-10 text-center text-white/50">Ainda não existem pedidos registrados.</div> : <div className="overflow-x-auto rounded-3xl border border-white/10"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-white/[0.04] text-[10px] uppercase tracking-widest text-white/40"><tr><th className="px-5 py-4">Referência</th><th className="px-5 py-4">Cliente</th><th className="px-5 py-4">Total</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Criado em</th></tr></thead><tbody>{orders.data?.map((order) => <tr key={order.id} className="border-t border-white/10"><td className="px-5 py-4 font-mono text-xs text-[#6df4ff]">{order.externalReference}</td><td className="px-5 py-4 text-white/70">{order.payerEmail ?? "Não informado"}</td><td className="px-5 py-4 font-bold">R$ {(order.totalAmountCents / 100).toFixed(2).replace('.', ',')}</td><td className="px-5 py-4"><span className="rounded-full bg-white/10 px-3 py-1 text-xs font-bold">{statusLabel[order.status] ?? order.status}</span></td><td className="px-5 py-4 text-white/45">{new Date(order.createdAt).toLocaleString("pt-BR")}</td></tr>)}</tbody></table></div>}</main></div>;
}
