import { Link, useRoute } from "wouter";
import { ArrowLeft, ShieldCheck } from "lucide-react";

const content = {
  privacidade: { title: "Política de privacidade", intro: "Como a Gamers RTF trata os dados usados para processar sua compra.", sections: [["Dados coletados", "Coletamos nome, CPF, data de nascimento, endereço, telefone e e-mail quando você inicia uma compra. Esses dados são usados para pagamento, envio, atendimento e cumprimento de obrigações legais."], ["Segurança", "Os dados de pagamento são processados pelo Mercado Pago. A Gamers RTF não solicita nem armazena a senha do seu cartão."], ["Seus direitos", "Você pode solicitar acesso, correção ou exclusão dos dados pessoais pelos canais de atendimento da loja, respeitadas as obrigações legais de guarda."]] },
  trocas: { title: "Trocas e devoluções", intro: "Regras simples para você comprar com tranquilidade.", sections: [["Prazo", "Solicite a troca ou devolução em até 7 dias corridos após o recebimento, conforme as regras aplicáveis às compras online."], ["Condições", "O produto deve ser devolvido com acessórios, manuais e embalagem sempre que possível. Produtos com sinais de mau uso podem passar por análise."], ["Atendimento", "Entre em contato com a Gamers RTF informando o número do pedido e o motivo da solicitação. A equipe orientará os próximos passos."]] },
  termos: { title: "Termos de uso", intro: "Condições para utilizar a loja Gamers RTF.", sections: [["Pedidos", "Os preços, disponibilidade e condições promocionais são apresentados na página do produto e podem ser alterados para novos pedidos."], ["Pagamento", "O pedido somente será separado após a confirmação do pagamento pelo Mercado Pago."], ["Responsabilidade", "As informações fornecidas no checkout devem ser verdadeiras e completas, especialmente o endereço de entrega e o e-mail de contato."]] },
} as const;

export default function LegalPage() {
  const [, params] = useRoute("/legal/:page");
  const page = content[(params?.page ?? "privacidade") as keyof typeof content] ?? content.privacidade;
  return <div className="site-shell min-h-screen bg-[#08090d] text-white"><header className="border-b border-white/10"><div className="container flex h-20 items-center justify-between"><Link href="/" className="font-black tracking-tight">GAMERS <span className="text-[#6df4ff]">RTF</span></Link><Link href="/" className="flex items-center gap-2 text-xs font-black uppercase tracking-[0.12em] text-white/55 hover:text-white"><ArrowLeft className="h-4 w-4" /> Voltar</Link></div></header><main className="container max-w-4xl py-20"><div className="eyebrow"><span /> Gamers RTF</div><h1 className="mt-5 text-4xl font-black tracking-[-0.06em] sm:text-6xl">{page.title}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-white/50">{page.intro}</p><div className="mt-12 grid gap-4">{page.sections.map(([title, text]) => <section key={title} className="rounded-3xl border border-white/10 bg-white/[0.03] p-6 sm:p-8"><h2 className="text-xl font-black">{title}</h2><p className="mt-3 leading-7 text-white/55">{text}</p></section>)}</div><div className="mt-8 flex items-center gap-2 text-xs text-white/35"><ShieldCheck className="h-4 w-4 text-[#6df4ff]" /> Última atualização: setembro de 2026</div></main></div>;
}
