export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  mercadoPagoAccessToken: process.env.MP_ACCESS_TOKEN ?? process.env.MERCADO_PAGO_ACCESS_TOKEN ?? "",
  mercadoPagoPublicKey: process.env.VITE_MERCADO_PAGO_PUBLIC_KEY ?? "",
  mercadoPagoWebhookSecret: process.env.MERCADO_PAGO_WEBHOOK_SECRET ?? "",
  publicAppUrl: process.env.PUBLIC_APP_URL ?? "",
  correiosAccessToken: process.env.CORREIOS_ACCESS_TOKEN ?? "",
  correiosOriginCep: process.env.CORREIOS_ORIGIN_CEP ?? "",
  correiosContract: process.env.CORREIOS_CONTRACT ?? "",
  correiosDr: process.env.CORREIOS_DR ?? "",
  correiosPacCode: process.env.CORREIOS_PAC_CODE ?? "03298",
  correiosSedexCode: process.env.CORREIOS_SEDEX_CODE ?? "03220",
  correiosPriceBaseUrl: process.env.CORREIOS_PRICE_BASE_URL ?? "https://api.correios.com.br/preco/v1",
  correiosDeadlineBaseUrl: process.env.CORREIOS_DEADLINE_BASE_URL ?? "https://api.correios.com.br/prazo/v1",
};
